# This code was originally written by Josh Shapiro
# for the Childhood Cancer Data Lab, an initiative of Alexs Lemonade Stand Foundation.
# https://github.com/AlexsLemonade/refinebio-examples/blob/33cdeff66d57f9fe8ee4fcb5156aea4ac2dce07f/.github/workflows/style-and-sp-check.yml#L1

# Adapted for this jhudsl repository by Candace Savonen Apr 2021

name: Test build of Dockerfile

# Controls when the action will run. Triggers the workflow for a pull request for
# master
on:
  release:
    types:
      - created
  pull_request:
    branches:
      - 'main'
    paths: [ docker/Dockerfile, docker/github_package_list.tsv ]
  workflow_dispatch:
    inputs:
      dockerhubpush:
        description: 'Push to Dockerhub?'
        required: true
        default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: login as jhudsl-robot
        run: |
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"

      - name: Don't re-test if this is a sync branch
        if: ${{ github.head_ref == 'repo-sync/OTTR_Template/default' }}
        run: |
          echo This was tested on OTTR_Template no need to re-run

      # Set up Docker build
      - name: Set up Docker Buildx
        if: ${{ github.head_ref != 'repo-sync/OTTR_Template/default' }}
        uses: docker/setup-buildx-action@v1

      # Setup layer cache
      - name: Cache Docker layers
        if: ${{ github.head_ref != 'repo-sync/OTTR_Template/default' }}
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Set up Docker build
      - name: Set up Docker Build
        if: ${{ github.head_ref != 'repo-sync/OTTR_Template/default' }}
        uses: docker/setup-buildx-action@v1

      - name: Get token
        if: ${{ github.head_ref != 'repo-sync/OTTR_Template/default' }}
        run: echo ${{ secrets.GH_PAT }} > docker/git_token.txt

      # Build docker image
      - name: Build Docker image
        if: ${{ github.head_ref != 'repo-sync/OTTR_Template/default' }}
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: docker
          file: docker/Dockerfile
          tags: jhudsl/course_template

      # Login to Dockerhub
      - name: Login to DockerHub
        if: ${{ github.event.inputs.dockerhubpush != 'false' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push the Docker image if set to true from a manual trigger
      - name: Push Docker image if manual trigger set to true
        if: ${{ github.event.inputs.dockerhubpush != 'false' }}
        run: docker push jhudsl/course_template

      - name: Get the version
        if: ${{ github.head_ref != 'repo-sync/OTTR_Template/default' }}
        id: get_version
        run: |
          echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)

      # Push the Docker image if it is a release
      - name: Push Docker image if release
        if: ${{ github.event_name == 'release' }}
        run: |
          docker tag jhudsl/course_template:latest jhudsl/course_template:${{ steps.get_version.outputs.version }}
          docker push jhudsl/course_template:${{ steps.get_version.outputs.version }}
