# Candace Savonen Aug 2021

name: Sync Files
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Run Mechanics File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_BODY: release-${{ steps.get_version.outputs.version }}
