# Candace Savonen Oct 2021

name: Render R Example

# Controls when the action will run. Triggers the workflow on push
# events only for the master branch
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'r-examples/r-heatmap-final/*'

jobs:
  render-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      # Run R analysis
      - name: Run R analysis example
        run: |
          docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          jhudsl/reproducible-r \
          bash r-examples/r-heatmap-final/run_analysis.sh

      - name: Commit rendered R example files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git add --force r-examples/r-heatmap-final/*
          git commit -m 'Render R example' || echo "No changes to commit"
          git push origin || echo "No changes to push"
