
# Candace Savonen Dec 2021

name: Style and spell check R markdowns

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "style and check"
  style-n-check:
    runs-on: ubuntu-latest
    container:
      image: jhudsl/course_template

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: login as jhudsl-robot
        run: |
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"

      - name: Run spell check
        id: spell_check_run
        run: |
          results=$(Rscript "scripts/spell-check.R")
          echo "::set-output name=sp_chk_results::$results"
          cat resources/spell_check_results.tsv

      - name: Archive spelling errors
        uses: actions/upload-artifact@v2
        with:
          name: spell-check-results
          path: resources/spell_check_results.tsv

      - name: Spell check errors
        run: |
          # Get on the preview branch if it exists. If it doesn't create it.
          branch_name='preview-${{ github.event.pull_request.number }}'
          git rev-parse --quiet --verify $branch_name >/dev/null && exists=true || exists=false

          if [[ $exists == true ]];
          then
            git checkout $branch_name
            git pull --set-upstream origin $branch_name --allow-unrelated-histories
          else
            git checkout -b $branch_name
          fi

          git add --force resources/spell_check_results.tsv
          git commit -m 'Add spell check file'
          git push --force --set-upstream origin $branch_name

      - name: Build components of the spell check comment
        id: build-components
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          branch_name='preview-${{ github.event.pull_request.number }}'
          sp_error_url=https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/$branch_name/resources/spell_check_results.tsv
          echo ::set-output name=time::$(date +'%Y-%m-%d')
          echo ::set-output name=commit_id::$GITHUB_SHA
          echo ::set-output name=sp_error_url::$sp_error_url

      # Handle the commenting
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: spelling errors

      - name: Spelling errors!
        if: ${{ steps.spell_check_run.outputs.sp_chk_results >= 3 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: There are spelling errors that need to be addressed. [Read this guide for more info](https://github.com/jhudsl/OTTR_Template/wiki/Spell-check).

            [Download the errors here.](${{ steps.build-components.outputs.sp_error_url }})
            _Comment updated at ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_
          edit-mode: replace

      - name: Check spell check results - fail if too many errors
        if: ${{ steps.spell_check_run.outputs.sp_chk_results >= 3 }}
        run: exit 1

      - name: No spelling errors
        if: ${{ steps.spell_check_run.outputs.sp_chk_results < 3 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            No spelling errors! :tada:

            _Comment updated at ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_
          edit-mode: replace

      - name: Run styler
        run: Rscript -e "styler::style_file(list.files(pattern = 'Rmd$', recursive = TRUE, full.names = TRUE));warnings()"

      - name: Commit styled files
        run: |
          git add \*.Rmd
          git add resources/spell_check_results.tsv
          git commit -m 'Style Rmds' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
