# Adapted from https://github.com/marketplace/actions/url-checker by Candace Savonen

# This github actions tests URLs in the Rmd files, README, and CONTRIBUTING.md
name: Check URLs

# This will be run upon PRs to main
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

# Here's the main action of checking URLs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: URLs-checker
        uses: urlstechie/urlchecker-action@master
        with:
          # Delete the cloned repository after running URLchecked (default is false)
          cleanup: true

          # A comma-separated list of file types to cover in the URL checks
          file_types: .Rmd

          # Choose whether to include file with no URLs in the prints.
          print_all: false

          # A comma separated links to exclude during URL checks
          exclude_urls: https://jhudatascience.org/{Course_Name}}

          # choose if the force pass or not
          force_pass : true
